Repository Winnie-The-POO-ARGBroker/Winnie-The-Food, pull requests merged in 2025-09, with the labels that each got.

#80 Actualización Portfolio Franco, Link al Css
  portfolios/franco/index.html
Labels: portfolio, fix

#102 Correcciones estilos portfolio Rodrigo
  History/portfolios/franco/index.html
  History/portfolios/rodrigo/index.html
Labels: fix

#122 Carga de avances en la rama release
  .vscode/settings.json
  History/.vscode/extensions.json
  History/.vscode/launch.json
  History/.vscode/settings.json
  History/.vscode/tasks.json
  assets/header.png
  package-lock.json
  package.json
  server/db.json
  src/app/app.config.ts
  src/app/app.routes.ts
  src/app/auth/auth.guard.ts
  src/app/auth/login/login.css
  src/app/auth/login/login.html
  src/app/auth/login/login.ts
  src/app/auth/register/register.css
  src/app/auth/register/register.html
  src/app/auth/register/register.ts
  src/app/models/categories-models.ts
  src/app/models/receta-model.ts
  src/app/pages/home/home.css
  src/app/pages/home/home.html
  src/app/pages/home/home.ts
  src/app/recipes/all-recipes/all-recipes.html
  src/app/recipes/all-recipes/all-recipes.ts
  src/app/recipes/dashboard-recipes/dashboard-recipes.css
  src/app/recipes/dashboard-recipes/dashboard-recipes.html
  src/app/recipes/dashboard-recipes/dashboard-recipes.ts
  src/app/recipes/detail-recipe/detail-recipe.css
  src/app/recipes/detail-recipe/detail-recipe.html
  src/app/recipes/detail-recipe/detail-recipe.ts
  src/app/recipes/new-recipe/new-recipe.store.ts
  src/app/recipes/new-recipe/new-recipe.ts
  src/app/recipes/new-recipe/steps/step-basic-info/step-basic-info.css
  src/app/recipes/new-recipe/steps/step-basic-info/step-basic-info.html
  src/app/recipes/new-recipe/steps/step-basic-info/step-basic-info.ts
  src/app/recipes/new-recipe/steps/step-ingredients/step-ingredients.css
  src/app/recipes/new-recipe/steps/step-ingredients/step-ingredients.html
  src/app/recipes/new-recipe/steps/step-ingredients/step-ingredients.ts
  src/app/recipes/new-recipe/steps/step-process-tips/step-process-tips.html
  src/app/recipes/new-recipe/steps/step-process-tips/step-process-tips.ts
  src/app/services/auth.service.ts
  src/app/services/recipes.service.ts
  src/app/shared/components/categories/categories.css
  src/app/shared/components/categories/categories.html
  src/app/shared/components/categories/categories.ts
  src/app/shared/components/empty-state/empty-state.css
  src/app/shared/components/empty-state/empty-state.html
  src/app/shared/components/empty-state/empty-state.spec.ts
  src/app/shared/components/empty-state/empty-state.ts
  src/app/shared/components/featured/featured.css
  src/app/shared/components/featured/featured.html
  src/app/shared/components/featured/featured.ts
  src/app/shared/components/menu/menu.html
  src/app/shared/components/menu/menu.ts
  src/main.ts
Labels: new release
